### ISSUE TITLE
[BUG] neural fails if user settings exist but contain no neural config

### ISSUE THREAD

**Issue by rm-minus-rf** [rspamd/rspamd#3270]
### Prerequisites

**Describe the bug**
neural.lua fails to use default config as fallback, if [user settings](https://rspamd.com/doc/configuration/settings.html) are defined but do not contain neural settings.

While the user settings are in place, the only relevant messages for a mail in the log are:
```
rspamd[12589]: <876954>; lua; settings.lua:311: applied settings id mx(3510803770); priority low
rspamd[12589]:neural.lua:346: no ann defined in SHORT for settings id 3510803770
rspamd[12589]:neural; neural.lua:1214: settings not found in rule SHORT
```

But if i remove the user settings, it works again:
```
rspamd[12753]: <876954>; lua; settings.lua:311: applied settings id mx(3510803770); priority low
rspamd[12753]: neural.lua:346: no ann defined in SHORT for settings id 3510803770
rspamd[12753]: <062eab>; neural; neural.lua:342: no ann loaded for SHORT:default
rspamd[12753]: <062eab>; lua; neural.lua:310: created new ANN profile for SHORT:default, data stored at prefix rn_SHORT_default_dodfj9ib_0
 rspamd[12753]: <062eab>; lua; neural.lua:478: cannot learn ham ANN SHORT:default: sampled out with probability 1 (1 vectors stored)
```

Adding debug messages to neural.lua i tracked it down to:
```
--- /usr/share/rspamd/plugins/neural.lua        2020-02-21 10:45:45.583261052 +0100
+++ /usr/share/rspamd/plugins/neural.lua.org    2020-02-21 10:45:22.087619866 +0100
@@ -264,7 +264,7 @@

   local set = rule.settings[sid]

-  if not set then set = -1 end
+  if not set then return nil end

   while type(set) == 'number' do
     -- Reference to another settings!
```
If i am correct, then this will fall back to the default config for neural ('-1' is the numeric id fo r default) if no specific settings are found for the user settings ('sid' is the numeric id for the user settings id applied to the task).

So finally my two questions:
1) Is this fix correct?
2) What is the correct way to define neural settings via user settings like it is mentioned on the  [neural module page](https://rspamd.com/doc/modules/neural.html#settings-usage)? I could not figure where to add them (local.d/settings.conf?) and what keys are needed...

### Steps to Reproduce
1. Have user settings like this:
local.d/settings.conf
```
mx {                                                                                                    
  priority = high;
  id = "mx"; 
  apply {                                                                                               
    symbols [
      "INBOUND_MAIL"                                                                                    
    ];                                                                                                  
  }
}

relay {
  priority = high;
  id = "relay";
  apply {
    groups_disabled = ["policies","surbl","headers","upstream_spam_filters","excessqp","mua","reputation","experimental","whitelist","subject","excessb64"];
    symbols [                                                                                           
      "OUTBOUND_MAIL"                                                                                   
    ];
    actions {
      greylist = null;
      rewrite_subject = null;                                                                           
    }
  } 
} 
```
2. use neural module
3. Send test mails

**Expected behavior**
neural should fall back to the default config from neural.conf if no specific config for the settings-id is found.

### Versions
tested with 
- rspamd 2.3 (rpm) @ RHEL 7.7
- rspamd 2.2 (rpm) @ RHEL 7.7

### Additional Information
I am aware, that the github issues is the wrong place to ask questions like "how do i configure" ... but because it is directly related to the possible bug, i still hope you could be willing to answer it ... or even add it to the documentation :-)
And also: Thanks for your hard work, rspamd is really cool software!

**Comment by vstakhov** [comment]
That's a good place for such a detailed investigation, thank you! I have checked the code and I'm still not convinced that it should be in the way you are suggesting.

Let's imagine that we have 2 sets: inbound and outbound. Inbound is defined implicitly by setting no settings-id. We want that our neural network works just for inbound. So we can write something like:

```
rules {
  default {
   ...
  }
}
```

So this rule will be applied merely for `-1` settings id and nothing else. If we have settings-id == outbound then this ANN will not be touched at all. With your change, that will not be satisfied and ANN will be applied for both ids.

So I would suggest to use some other method to share neural networks over settings. Probably, add something like `fallback_settings = true`. We would also need something like `forbidden_settings` to disallow this behaviour for specific settings ids.

**Comment by vstakhov** [comment]
I'm open for suggestions. In fact, I plan to release 2.4 in these two days so I could fix that before release.

**Comment by rm-minus-rf** [comment]
Hmm, i think i inspired you for a feature, without really understanding what i was talking about ;-)

My problem was that i did not find a way to bring neural to work while having the mx/relay (IN/OUT) user settings active.
Based on your response (and another look at the sources), i now think that 'allowed_settings' inside a neural rule is the correct to activate this rule for either 'mx' or 'relay':
```
rules {                                                                                                 
  "SHORT_IN" {                                                                                             
   ...

   allowed_settings = "mx";
  } 

  "SHORT_OUT" {                                                                                             
   ...

   allowed_settings = "relay";
  } 
} 

```

Unfortunately this will not work.
What would be the correct way to use 'allowed_settings' to have seperate IN/OUT Neural networks?

Your idea with "fallback_settings = true" would allow us to use the same network for IN/OUT, is that right? That might also be helpful in same scenarios, but is not needed for us right now.

**Comment by vstakhov** [comment]
AFAIR, allowed_settings should be an array.

**Comment by rm-minus-rf** [comment]
Ah sorry, i was sloppy while writing the example and forgot to mention, that i already tried arrays: `` allowed_settings = ["mx"];``
This resulted in: 
```
cfg; rspamd_lua_run_config_post_init: cannot run config post init script: /usr/share/rspamd/plugins/neural.lua: attempt to index local 'selt' (a nil value); trace: [1]:{/usr/share/rspamd/plugins/neural.lua
```
Having another look at the neural.lua sources i think i found the problem: The conversion from the settings-id string "mx" to the numerical settings-id seems to be missing.
If i use the numerical id in neural.conf then it works as expected! `` allowed_settings = [3510803770];``
But i guess that is not intended behaviour, as the user should not have to know the numeric id, right?

What about:
```
--- /usr/share/rspamd/plugins/neural.lua	2020-02-25 10:39:19.979868608 +0100
+++ /usr/share/rspamd/plugins/neural.lua.org-2.3-1	2020-02-25 10:02:37.059223328 +0100
@@ -1271,11 +1271,7 @@
     -- We set table rule.settings[id] -> { name = name, symbols = symbols, digest = digest }
     for s,_ in pairs(rule.allowed_settings) do
       -- Here, we have a name, set of symbols and
-      local settings_id = s
-      if type(settings_id) ~= 'number' then 
-        settings_id = lua_settings.numeric_settings_id(s)
-      end
-      local selt = lua_settings.settings_by_id(settings_id)
+      local selt = lua_settings.settings_by_id(s)
 
       local nelt = {
         symbols = selt.symbols, -- Already sorted
@@ -1290,14 +1286,14 @@
             lua_util.debugm(N, rspamd_config,
                 'added reference from settings id %s to %s; same symbols',
                 nelt.name, ex.name)
-            rule.settings[settings_id] = id
+            rule.settings[s] = id
             nelt = nil
           end
         end
       end
 
       if nelt then
-        rule.settings[settings_id] = nelt
+        rule.settings[s] = nelt
         lua_util.debugm(N, rspamd_config, 'added new settings id %s to %s',
             nelt.name, rule.prefix)
       end


--- /usr/share/rspamd/lualib/lua_settings.lua	2020-02-25 10:04:16.679027952 +0100
+++ /usr/share/rspamd/lualib/lua_settings.lua.org-2.3-1	2020-02-25 10:02:58.439181404 +0100
@@ -169,7 +169,6 @@
 
   return ret
 end
-exports.numeric_settings_id = numeric_settings_id
 
 -- Used to do the following:
 -- If there is a group of symbols_allowed, it checks if that is an array

```

**Comment by vstakhov** [comment]
Grr, your patches are reversed so it's v. confusing to read them.

**Comment by rm-minus-rf** [comment]
Oh, sorry, you are right. I will pay attention to the file order next time.

**Comment by vstakhov** [comment]
Could you please test my change? It seems to be identical to one you've suggested but I want to double check.

**Comment by rm-minus-rf** [comment]
Used the neural.lua from your commit and i looks good to me:

With ``allowed_settings = ["mx"]``:
```
Feb 25 14:50:02 rspamd[27210]: <f4j6ro>; neural; neural.lua:1217: use dynamic cfg based profile for SHORT (default)
Feb 25 14:50:02 rspamd[27210]: <f4j6ro>; neural; neural.lua:1217: use dynamic cfg based profile for SHORT (mx)
Feb 25 14:50:02 rspamd[27210]: <f4j6ro>; neural; neural.lua:1324: added new settings id mx(3510803770) to SHORT
Feb 25 14:50:02 rspamd[27219]: <f4j6ro>; neural; neural.lua:1112: try_load_ann: process element SHORT:default
Feb 25 14:50:02 rspamd[27219]: <f4j6ro>; neural; neural.lua:1112: try_load_ann: process element SHORT:mx
...
Feb 25 14:50:03 rspamd[27217]: <f4j6ro>; neural; neural.lua:1112: try_train_ann: process element SHORT:mx
Feb 25 14:50:03 rspamd[27217]: <f4j6ro>; neural; neural.lua:1112: try_train_ann: process element SHORT:default
...testmail sent here...
Feb 25 14:50:42 rspamd[27219]: <587234>; lua; settings.lua:168: applied settings id mx(3510803770)
Feb 25 14:50:49 rspamd[27219]: <587234>; neural; neural.lua:337: no ann loaded for SHORT:mx
Feb 25 14:50:49 rspamd[27219]: <587234>; lua; neural.lua:305: created new ANN profile for SHORT:mx, data stored at prefix rn_SHORT_mx_h6rs4aze_0
Feb 25 14:50:49 rspamd[27219]: <587234>; neural; neural.lua:456: add train data for ANN rule SHORT:mx, save ham vector of 574 elts in rn_SHORT_mx_h6rs4aze_0_ham key; 134 bytes compressed

```


With ``allowed_settings = "all"``:
```
Feb 25 14:55:10 rspamd[27549]: <jwy66j>; neural; neural.lua:1217: use dynamic cfg based profile for SHORT (default)
Feb 25 14:55:10 rspamd[27549]: <jwy66j>; neural; neural.lua:1217: use dynamic cfg based profile for SHORT (mx)
Feb 25 14:55:10 rspamd[27549]: <jwy66j>; neural; neural.lua:1324: added new settings id mx(3510803770) to SHORT
Feb 25 14:55:10 rspamd[27549]: <jwy66j>; neural; neural.lua:1217: use dynamic cfg based profile for SHORT (relay)
Feb 25 14:55:10 rspamd[27549]: <jwy66j>; neural; neural.lua:1324: added new settings id relay(2307231189) to SHORT
Feb 25 14:55:10 rspamd[27559]: <jwy66j>; neural; neural.lua:1112: try_load_ann: process element SHORT:mx
Feb 25 14:55:10 rspamd[27559]: <jwy66j>; neural; neural.lua:1112: try_load_ann: process element SHORT:default
Feb 25 14:55:10 rspamd[27559]: <jwy66j>; neural; neural.lua:1112: try_load_ann: process element SHORT:relay
...
Feb 25 14:55:10 rspamd[27557]: <jwy66j>; neural; neural.lua:1112: try_train_ann: process element SHORT:mx
Feb 25 14:55:10 rspamd[27557]: <jwy66j>; neural; neural.lua:1112: try_train_ann: process element SHORT:default
Feb 25 14:55:10 rspamd[27557]: <jwy66j>; neural; neural.lua:1112: try_train_ann: process element SHORT:relay
...testmail sent here...
Feb 25 14:55:12 rspamd[27559]: <2b8a73>; lua; settings.lua:168: applied settings id mx(3510803770)
Feb 25 14:55:14 rspamd[27559]: <2b8a73>; neural; neural.lua:337: no ann loaded for SHORT:mx
Feb 25 14:55:14 rspamd[27559]: <2b8a73>; lua; neural.lua:305: created new ANN profile for SHORT:mx, data stored at prefix rn_SHORT_mx_h6rs4aze_0
Feb 25 14:55:14 rspamd[27559]: <2b8a73>; neural; neural.lua:456: add train data for ANN rule SHORT:mx, save ham vector of 574 elts in rn_SHORT_mx_h6rs4aze_0_ham key; 134 bytes compressed
```


Without any ``allowed_settings`` line in neural.conf:
```
Feb 25 14:56:31 rspamd[27661]: <ogg65t>; neural; neural.lua:1217: use dynamic cfg based profile for SHORT (default)
Feb 25 14:56:31 rspamd[27670]: <ogg65t>; neural; neural.lua:1112: try_load_ann: process element SHORT:default
Feb 25 14:56:31 rspamd[27668]: <ogg65t>; neural; neural.lua:1112: try_train_ann: process element SHORT:default
...testmail sent here...
Feb 25 14:56:33 rspamd[27671]: <84b744>; lua; settings.lua:168: applied settings id mx(3510803770)
Feb 25 14:56:35 rspamd[27671]: <84b744>; neural; neural.lua:341: no ann defined in SHORT for settings id 3510803770
Feb 25 14:56:35 rspamd[27671]: <84b744>; neural; neural.lua:1197: settings not found in rule SHORT
```
(rn_* deleted in redis on testserver before each run)

Again, sorry for the reversed patch order.

**Comment by rm-minus-rf** [comment]
There is a problem when the training condition for a rule is not satisfied:
```
<fdbbe6>; neural; neural.lua:339: no ann loaded for SHORT:mx
<fdbbe6>; task; lua_metric_symbol_callback: call to (NEURAL_LEARN) failed (2): /usr/share/rspamd/plugins/neural.lua:517: attempt to index field 'ann' (a nil value); trace: [1]:{/usr/share/rspamd/plugins/neural.lua:517 - ann_push_task_result [Lua]}; [2]:{/usr/share/rspamd/plugins/neural.lua:1212 - <unknown> [Lua]};
```

The problem is a debug message (starting in line 515) containing ``set.ann.redis_key`` when ``set.ann`` is not always set in the else block for ``if learn_spam or learn_ham then``:
```
  ...
  if learn_spam or learn_ham then
    ...
    if set.can_store_vectors then
      if not set.ann then
        set.ann = new_ann_profile(task, rule, set, 0)  <-- "set.ann" loaded here
    ...
  else
    lua_util.debugm(N, task,
        'do not push data to key %s: train condition not satisfied; reason: %s',
        set.ann.redis_key,  <-- but "set.ann.redis_key" used here
        skip_reason)
  end
```

No patch this time, cause i am not familiar enought with neural.lua to suggest a meaningful debug message withouth the redis_key here.
And sorry for reporting this after the 2.4 release and not before. All my testmails with what i tested your changes were either spammy or hammy enough to set learn_spam or learn_ham. :-(

**Comment by vstakhov** [comment]
It should be fixed now, I'd appreciate if you can test it as I want to do a correction release.

**Comment by rm-minus-rf** [comment]
Looks good to me.

```
neural; neural.lua:339: no ann loaded for SHORT:mx
neural; neural.lua:515: do not push data to key nil: train condition not satisfied; reason: score > ham_score: 8.782449 > -4.000000

```

To be honest, i have no idea how to test the second case (else block at line 511).
What must happen for ``set.can_store_vectors`` to be false? No connection to redis?

**Comment by andryyy** [comment]
Looks good here, too.

**Comment by t0rzz** [comment]
Still happening in Debian 10:

`call to (NEURAL_LEARN) failed (2): /usr/share/rspamd/plugins/neural.lua:517: attempt to index field 'ann' (a nil value); trace: [1]:{/usr/share/rspamd/plugins/neural.lua:517 - ann_push_task_result [Lua]}; [2]:{/usr/share/rspamd/plugins/neural.lua:1212 - [Lua]};`

**Comment by heraklit256** [comment]
Can confirm this on Debian 10, too:
```
2020-03-15 14:41:33 #7678(rspamd_proxy) <008f85>; proxy; lua_metric_symbol_callback: call to (NEURAL_LEARN) failed (2): /usr/share/rspamd/plugins/neural.lua:517: attempt to index field 'ann' (a nil value); trace: [1]:{/usr/share/rspamd/plugins/neural.lua:517 - ann_push_task_result [Lua]}; [2]:{/usr/share/rspamd/plugins/neural.lua:1212 - <unknown> [Lua]};
```

**Comment by andryyy** [comment]
If I see this correctly, the packages have not been updated yet. So that's expected.

**Comment by heraklit256** [comment]
Oh, I see. Thanks for mentioning it. :-)

**Comment by t0rzz** [comment]
After the latest update it's not showing "learn error: Unknown statistics error, found when storing data on backend; classifier: bayes" every 24 hours. Any way to fix it? Should I open another bug or is it related?
