### ISSUE TITLE
[BUG] add_smtp_user=false doesn't affect Authentication-Results header

### ISSUE THREAD

**Issue by dadosch** [rspamd/rspamd#3728]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Setting ''add_smtp_user = false;'' doesn't change the addition of smtp.auth= in Authentication-Results header.

### Steps to Reproduce

1. Set in local.d/milter_headers.conf:
```
routines {
  authentication-results {
   add_smtp_user = false;
  }
}
```
2. Restart rspamd, verify config change with rspamadm configdump
3. Send an email authenticated from smtp, see that smtp.auth= is present, despite the setting

**Expected behavior**
smtp.auth should not be present, as that is what the setting is for

### Versions
`Rspamd daemon version 2.7`, Ubuntu Focal

### Additional Information
Workaround: Patching /usr/share/rspamd/lualib/lua_auth_results.lua to set the default value of `add_smtp_user` to false.

**Comment by vstakhov** [comment]
I have added a patch to fix this issue.

**Comment by dadosch** [comment]
Fixed by https://github.com/rspamd/rspamd/commit/5d70e9fae9341ab6f38f93d4bf6a403e82022488, so it can be closed

**Comment by janedenone** [comment]
I experience the same issue with Rspamd 3.1.

**Comment by TCB13** [comment]
Working for me at rspamd 3.5.

**Comment by janedenone** [comment]
> Working for me at rspamd 3.5.

The issue persists for me (rspamd 3.5). As soon as I set `skip_authenticated = false;` in `milter_headers.conf`, messages sent by an authenticated user contain the following header:

```
Authentication-Results: ORIGINATING;
        auth=pass smtp.auth=abcde@domain.com smtp.mailfrom=fghji@domain.com
```

even though `milter_headers.conf` also contains:

```
routines {
   authentication_results {
     add_smtp_user = false;
   }
    x-rspamd-server {
        header = 'X-Rspamd-Server';
        hostname = 'mail.domain.com';
    }
}
```

**Comment by TCB13** [comment]
> > Working for me at rspamd 3.5.
> 
> The issue persists for me (rspamd 3.5). As soon as I set `skip_authenticated = false;` in `milter_headers.conf`, messages sent by an authenticated user contain the following header:
> 
> ```
> Authentication-Results: ORIGINATING;
>         auth=pass smtp.auth=abcde@domain.com smtp.mailfrom=fghji@domain.com
> ```
> 
> even though `milter_headers.conf` also contains:
> 
> ```
> routines {
>    authentication_results {
>      add_smtp_user = false;
>    }
>     x-rspamd-server {
>         header = 'X-Rspamd-Server';
>         hostname = 'mail.domain.com';
>     }
> }
> ```

I simply added the following to and restarted rspamd:

````

**Comment by janedenone** [comment]
I used `authentication_results` instead of `authentication-results` – very embarassing. Sorry for the noise.
